### ISSUE TITLE
Bad installation path and lib prefix for 64 bit version.

### ISSUE THREAD

**Issue by AS383** [raboof/sfArkLib#11]
On 64 bit ROSA Linux a library compiled with **lib** prefix instead of **lib64**. Also it is installed on /usr/local/**lib/** directory, but not /usr/local/**lib64/**.

**Comment by raboof** [comment]
Hmm, Debian appears to put 64-bit libraries in `.../lib` on a 64-bit system.. not sure what the right default would be here. What does the FHS say?

**Comment by AS383** [comment]
@raboof, [FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html#LIBLTQUALGTALTERNATEFORMATESSENTIAL) require separate catalogs for each binary format. Also lib can be symlink to the lib64 directory. Possible Debian use symlink.
> Hmm, Debian appears to put 64-bit libraries in .../lib on a 64-bit system.. not sure what the right default would be here. What does the FHS say?

**Comment by raboof** [comment]
Hm, looks like it says `/usr/lib<qual>` is an *optional* place for 'alternate' binary formats though - at least for my Debian installation /lib is not a symlink.

**Comment by mirabilos** [comment]
Debian uses the newer Multi-Arch specification.

My upcoming pull request makes it possible for ROSA Linux to override `${LIBDIR}` on the `make` command line.

**Comment by raboof** [comment]
should be fixed with #17
