### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by rubund** [raboof/sfArkLib#7]
Can you tag of a release? I'm working on a debian package.

**Comment by rekado** [comment]
I'm working on a package for Guix and I'd also appreciate a new tarball that includes the Makefile.  Right now I'm using a git checkout as the input rather than a release tarball, but that's a little ugly.

**Comment by raboof** [comment]
Tagged the current master as version 2.24

**Comment by raboof** [comment]
apt-ca
