### ISSUE TITLE
Apply Debian patches to build system

### ISSUE THREAD

**Issue by RossGammon** [raboof/sfArkLib#9]
Hi,
Ruben Undheim ruben.undheim@gmail.com recently packaged sfArkLib for Debian, and I am about to update to the latest release tag (2.24).
Ruben patched the build system in Debian to add sub-versions for the library name, and to install it correctly in the required location. He also linked to zlib directly so that software that links to sfArkLib so not need to link to zlib themselves.
I would be grateful if you would consider including these patches in the next release of SfArkLib.
A Pull Request is on the way.
Regards,
Ross Gammon

**Comment by raboof** [comment]
Hello Ross, 

Thanks for the PR! I added some questions there.


Kind regards,

Arnout

**Comment by mirabilos** [comment]
This can probably be closed now. If things work as expected and a new release is published, we can update the Debian package to match.

(I didn’t get a reply to the question for a testcase, though, but it’d probably belong into sfarkxtc instead anyway, so I think sfarklib could be released, unless there’s something still wrong.)
